/* Generated by Cython 0.29.26 */

#ifndef __PYX_HAVE__Artificials_CythonWrapped
#define __PYX_HAVE__Artificials_CythonWrapped

#include "Python.h"

#ifndef __PYX_HAVE_API__Artificials_CythonWrapped

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *_eTreatmentClean(PyObject *);

#endif /* !__PYX_HAVE_API__Artificials_CythonWrapped */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initArtificials_CythonWrapped(void);
#else
PyMODINIT_FUNC PyInit_Artificials_CythonWrapped(void);
#endif

#endif /* !__PYX_HAVE__Artificials_CythonWrapped */
