<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <IntelSWTools_ROOT>packages</IntelSWTools_ROOT>
    <IntelSWTools>$(IntelSWTools_ROOT)\2025.3\windows</IntelSWTools>
    <MKLIncludeDir>$(IntelSWTools_ROOT)\mkl\2025.3\include</MKLIncludeDir>
    <MKLLibDir>packages/intelmkl.static.win-x64.2026.0.0.901/build/native/win-x64</MKLLibDir>
    <OmpLibDir>packages/intelopenmp.devel.win.2026.0.0.944/build/native/win-x64</OmpLibDir>
    <IPPLibDir>$(IntelSWTools_ROOT)\ipp\2025.3\lib</IPPLibDir>
    <CPPLibDir>$(IntelSWTools_ROOT)\compiler\2025.3\lib</CPPLibDir>
    <DAALibDir>$(IntelSWTools_ROOT)\daal\2025.3\lib</DAALibDir>
    <CPPPath>$(IntelSWTools_ROOT)\redist\intel64_win\compiler</CPPPath>
    <Armadillo>$(WDataSci)\armadillo</Armadillo>
    <TBBLibDir>$(IntelSWTools_ROOT)\tbb\2025.3\lib\vc_mt</TBBLibDir>
  </PropertyGroup>
  <PropertyGroup>
    <IncludePath>$(WDSCppLib)\include;$(WDSCppLib)\..\WDS-C\include;$(Armadillo)\include;$(MKLIncludeDir);$(VC_IncludePath);$(WindowsSDK_IncludePath);$(IncludePath)</IncludePath>
    <LibraryPath>$(WDSCppLib)\lib;$(OmpLibDir);$(MKLLibDir);$(TBBLibDir);$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64);$(NETFXKitsDir)Lib\um\x64</LibraryPath>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <UseMpiLibrary>INTELMPI</UseMpiLibrary>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile />
    <Link>
      <LinkTimeCodeGeneration>UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
      <AdditionalLibraryDirectories>C:\dev\github\WDS-ModelSpec\WDS-Cpp\WDS\Comp\Matrix\packages\intelmkl.static.win-x64.2026.0.0.901\build\native\win-x64;C:\dev\github\WDS-ModelSpec\WDS-Cpp\WDS\Comp\Matrix\packages\intelmkl.static.cluster.win-x64.2026.0.0.901\build\native\win-x64;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <Lib>
      <AdditionalDependencies>
      </AdditionalDependencies>
    </Lib>
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
      <AdditionalIncludeDirectories>.\src;$(WDSCppLib)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="IntelSWTools_ROOT">
      <Value>$(IntelSWTools_ROOT)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="IntelSWTools">
      <Value>$(IntelSWTools)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="MKLIncludeDir">
      <Value>$(MKLIncludeDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="MKLLibDir">
      <Value>$(MKLLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="OmpLibDir">
      <Value>$(OmpLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="IPPLibDir">
      <Value>$(IPPLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="CPPLibDir">
      <Value>$(CPPLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="DAALibDir">
      <Value>$(DAALibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="CPPPath">
      <Value>$(CPPPath)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="Armadillo">
      <Value>$(Armadillo)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="TBBLibDir">
      <Value>$(TBBLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>