<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <xll_ROOT>$(CppLocalExternalPackages)\xll24</xll_ROOT>
    <xll_LIBDIR>$(xll_ROOT)</xll_LIBDIR>
    <xll_INCLUDE>$(xll_ROOT)\include</xll_INCLUDE>
    <Excel2013XLLSDK_ROOT>$(CppLocalExternalPackages)\Excel2013XLLSDK</Excel2013XLLSDK_ROOT>
    <Excel2013XLLSDK_LIBDIR>$(Excel2013XLLSDK_ROOT)\LIB\x64</Excel2013XLLSDK_LIBDIR>
    <Excel2013XLLSDK_INCLUDE>$(Excel2013XLLSDK_ROOT)\INCLUDE</Excel2013XLLSDK_INCLUDE>
  </PropertyGroup>
  <PropertyGroup>
    <TargetExt>.xll</TargetExt>
    <IncludePath>.\src-xll;$(xll_INCLUDE);.\src-ExcelSDK;$(Excel2013XLLSDK_INCLUDE);$(IncludePath)</IncludePath>
    <LibraryPath>$(xll_LIBDIR);$(Excel2013XLLSDK_LIBDIR);$(LibraryPath)</LibraryPath>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <UseIntelMKL>No</UseIntelMKL>
    <UseIntelDAAL>false</UseIntelDAAL>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <AdditionalOptions>/J %(AdditionalOptions)</AdditionalOptions>
      <PreprocessorDefinitions>_WINDLL;_SCL_SECURE_NO_WARNINGS;NOMINMAX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      <AdditionalDependencies>XLCALL32.LIB;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <ProjectReference>
      <UseLibraryDependencyInputs>
      </UseLibraryDependencyInputs>
    </ProjectReference>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="xll_ROOT">
      <Value>$(xll_ROOT)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="Excel2013XLLSDK_ROOT">
      <Value>$(Excel2013XLLSDK_ROOT)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xll_LIBDIR">
      <Value>$(xll_LIBDIR)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="Excel2013XLLSDK_LIBDIR">
      <Value>$(Excel2013XLLSDK_LIBDIR)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xll_INCLUDE">
      <Value>$(xll_INCLUDE)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="Excel2013XLLSDK_INCLUDE">
      <Value>$(Excel2013XLLSDK_INCLUDE)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>
