<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <WDSProject>WDS-ModelSpec</WDSProject>
    <WDSProjectBranch>master</WDSProjectBranch>
    <WDataSci>C:\dev\github</WDataSci>
    <WDSCppLib>$(WDataSci)\$(WDSProject)\WDS-Cpp</WDSCppLib>
    <WDSCLib>$(WDataSci)\$(WDSProject)\WDS-C</WDSCLib>
    <IntelSWTools>$(IntelSWTools_ROOT)\2025.3\windows</IntelSWTools>
    <TBBIncludeDir>$(IntelSWTools_ROOT)\tbb\2022.3\include</TBBIncludeDir>
    <TBBLibDir>packages/inteltbb.devel.win.2023.0.0.716/build/native/win-x64/</TBBLibDir>
    <MKLMajorVersion>2025</MKLMajorVersion>
    <MKLMinorVersion>3</MKLMinorVersion>
    <MKLProductDir>packages/intelmkl.static.win-x64.2026.0.0.901/build/native/win-x64</MKLProductDir>
    <IPPMajorVersion>2025</IPPMajorVersion>
    <IPPMinorVersion>3</IPPMinorVersion>
    <IPPIncludeDir>$(IntelSWTools_ROOT)\ipp\include</IPPIncludeDir>
    <DAALMajorVersion>2025</DAALMajorVersion>
    <DAALMinorVersion>3</DAALMinorVersion>
    <DAALProductDir>$(IntelSWTools_ROOT)</DAALProductDir>
    <DAALIncludeDir>$(DAALProductDir)\include</DAALIncludeDir>
    <DAALLibDir>$(DAALProductDir)</DAALLibDir>
  </PropertyGroup>
  <PropertyGroup>
    <IncludePath>$(WDSCppLib)\include;$(WDSCLib)\include;$(TBBIncludeDir);$(xll_ROOT);$(IncludePath)</IncludePath>
    <SourcePath>.\src;$(WDSCppLib)\WDS\src;$(WDSCLib)\WDS\src</SourcePath>
    <LibraryPath>$(WDSCppLib)\lib;$(TBBLibDir)\vc_mt;$(LibraryPath)</LibraryPath>
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <UseMpiLibrary>INTELMPI</UseMpiLibrary>
    <UseIntelTBB>false</UseIntelTBB>
    <UseIntelMKL>Sequential</UseIntelMKL>
    <UseIntelDAAL>Parallel_Static</UseIntelDAAL>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <LanguageStandard>stdcpplatest</LanguageStandard>
      <PreprocessorDefinitions>_WINDLL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <EnforceTypeConversionRules>true</EnforceTypeConversionRules>
      <AdditionalOptions>/J %(AdditionalOptions)</AdditionalOptions>
      <AdditionalIncludeDirectories>.\src;$(WDSCppLib)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <ProjectReference>
      <UseLibraryDependencyInputs>
      </UseLibraryDependencyInputs>
      <LinkLibraryDependencies>true</LinkLibraryDependencies>
    </ProjectReference>
    <Link />
    <Lib>
      <LinkTimeCodeGeneration>true</LinkTimeCodeGeneration>
    </Lib>
    <Link>
      <AdditionalLibraryDirectories>$(IPPLibDir);$(MKLLibDir);$(TBBLibDir);$(DAALibDir);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="WDataSci">
      <Value>$(WDataSci)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="WDSCppLib">
      <Value>$(WDSCppLib)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="WDSCLib">
      <Value>$(WDSCLib)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="IntelSWTools">
      <Value>$(IntelSWTools)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="TBBIncludeDir">
      <Value>$(TBBIncludeDir)</Value>
    </BuildMacro>
    <BuildMacro Include="TBBLibDir">
      <Value>$(TBBLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="MKLMajorVersion">
      <Value>$(MKLMajorVersion)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="MKLMinorVersion">
      <Value>$(MKLMinorVersion)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="MKLProductDir">
      <Value>$(MKLProductDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="IPPMajorVersion">
      <Value>$(IPPMajorVersion)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="IPPMinorVersion">
      <Value>$(IPPMinorVersion)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="IPPIncludeDir">
      <Value>$(IPPIncludeDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="DAALMajorVersion">
      <Value>$(DAALMajorVersion)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="DAALMinorVersion">
      <Value>$(DAALMinorVersion)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="DAALProductDir">
      <Value>$(DAALProductDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="DAALIncludeDir">
      <Value>$(DAALIncludeDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="DAALLibDir">
      <Value>$(DAALLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>